extends Node

signal inventory_tab_selected
signal inventory_slot_selected
signal inventory_updated
signal minigame_one_started
signal minigame_one_failed
signal minigame_one_defeated
signal ui_selected
signal inventory_closed
signal shop_slot_selected
